apiVersion: v1
kind: Service
metadata:
  name: nberic-task-tracker-web
  namespace: default
spec:
  selector:
    app: nberic-task-tracker-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 31130
  type: NodePort
